# Configuration file for Movie Vector Database Benchmark

data:
  path: "./data"              # Path to MovieLens dataset
  sample_size: 1000           # Number of movies to sample (null for full dataset)

embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"  # Embedding model
  batch_size: 32              # Batch size for embedding generation
  cache_path: "./embeddings_cache.parquet"         # Cache file for embeddings

databases:
  faiss:
    enabled: true
    index_path: "./faiss_index.bin"
    metadata_path: "./faiss_metadata.pkl"
  
  chroma:
    enabled: true
    persist_directory: "./chroma_db"
  
  qdrant:
    enabled: true               # Enable Qdrant (requires Docker)
    url: "http://localhost:6333"
    collection: "movies"
  
  milvus:
    enabled: true               # Enable Milvus (requires Docker)
    host: "localhost"
    port: "19530"
    collection: "movies"
  
  weaviate:
    enabled: false              # Disabled due to gRPC connection issues
    url: "http://localhost:8080"
  
  pinecone:
    enabled: false              # Set to true and provide API key to enable
    api_key: null               # Set your Pinecone API key or use PINECONE_API_KEY env var
    index_name: "movies"
    environment: "us-east-1-aws"
  
  topk:
    enabled: false              # Set to true and provide API key to enable
    api_key: null               # Set your TopK API key or use TOPK_API_KEY env var
    region: "aws-us-east-1-elastica"
    collection: "movies"

benchmark:
  top_k: 10                    # Number of results to retrieve per query
  query_count: 10              # Number of queries to run